### ISSUE TITLE
Can JAMIE work when no paired cells are available? (priors as a zero matrix)

### ISSUE THREAD

**Issue by AprilYuge** [Oafish1/ComManDo#4]

**Comment by Oafish1** [comment]
It can!  However, JAMIE works _much_ better with at least some correspondence information provided.  This can be from other methods or the dataset itself.  The prior correspondence matrix can also have values aside from 0 and 1, as well as multiple entries per row/column.  I can send you the paper and would be happy to answer any questions if you would like more details.

If you are not getting good alignment with few or no priors, you can also try steadily decreasing the argument `PF_Ratio` from 1 to 0, which will attempt to estimate the correspondence using a method similar to that in `UnionCom`.  `PF_Ratio` can be a value from 0 (full estimation) to 1 (full provided prior, default) where any value in-between uses a weighted average of the estimated and prior correspondence.  This argument is still experimental, however, and can have varied results.

Hope this helps!
