### ISSUE TITLE
Some potential bugs

### ISSUE THREAD

**Issue by bestadcarry** [Oafish1/ComManDo#5]
Hi, I am using JAMIE package. But it seems like there are some bugs in the methods JAMIE.project_jamie. If we use GPU, self.P has been placed on GPU in line [417](https://github.com/daifengwanglab/JAMIE/blob/b3bfcf54b107088242d891e17106b853a40af62b/jamie/jamie.py#L417). But then numpy function is applied on tensor self.P, like [np.abs](https://github.com/daifengwanglab/JAMIE/blob/b3bfcf54b107088242d891e17106b853a40af62b/jamie/jamie.py#L510) and [np.argwhere](https://github.com/daifengwanglab/JAMIE/blob/b3bfcf54b107088242d891e17106b853a40af62b/jamie/jamie.py#L512).  Errors are reported on my case.

**Comment by Oafish1** [comment]
Hello!  Thank you for your interest in JAMIE!  I appreciate the bug report.

I've released update 4.4.1 with commit b7d4c01 to add GPU support.  Please update and let me know if this resolves your issue.

Have a nice day!

**Comment by Oafish1** [comment]
Hi @bestadcarry, I'm going to close the issue since it's been inactive for a week, but please feel free to reopen it if you are having any more issues!

Have a nice day!
