### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by wrab12** [Oafish1/ComManDo#6]
Hello, could you provide the processed data, specifically the H5AD files? You can upload them to a file-sharing service. Thank you.

**Comment by Oafish1** [comment]
Hello!  Thank you for your interest in JAMIE.

I don't have the JAMIE-processed data offhand.  Instead, I have pre-trained models which can transform the data quickly.  If you have a specific condition (i.e. Developing Brain Imputation, Simulation Data Integration) from the paper in mind, I can run this and send it over as a csv file.

Alternatively, the pre-trained models from the paper are available [here](https://doi.org/10.24433/CO.0507883.v1) as `saved_models.tgz`.  I can also send over some slightly updated pre-trained models from the most recent version of the repository if you would prefer.

Hope this helps!

**Comment by wrab12** [comment]
I'm sorry for any confusion. What I want from you is to share the model's dataset, similar to the data in the 'data' directory inside the 'example' folder. Some datasets are provided directly, and for others, you've instructed me on how to obtain them. I'm wondering if there might be a more convenient way, such as uploading those datasets through a cloud storage service. This way, I could more easily use your model and help increase its impact.

**Comment by Oafish1** [comment]
Ah, my mistake.  I can certainly see how that would be inconvenient.  All of the data is available in a single tar-archive [here](https://doi.org/10.24433/CO.0507883.v1) as `data.tgz`.

However, the website seems to be down at the moment.  If it doesn't come online soon, I'll upload to another file-sharing website and send it over.

Hope this helps!

**Comment by wrab12** [comment]
Alright, thank you. My question has been resolved, and your work is excellent, very thorough. To be honest, I rarely come across such solid work. I hope this article gets more citations.

**Comment by Oafish1** [comment]
Thank you!  That's fantastic to hear!  If you have any more questions please don't hesitate to ask.

Have a nice day!
